Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,13 +19,20 @@ jobs:
           node-version: 20
           cache: npm
 
-      - name: Sync dependencies
+      - name: Clean install
         run: |
+          rm -rf node_modules
           npm install --legacy-peer-deps
 
-      - name: Build
+      - name: Build project
+        run: npm run build
+
+      - name: Ensure dist exists
         run: |
-          npm run build
+          if [ ! -d "dist" ]; then
+            echo "Build failed. dist folder not found."
+            exit 1
+          fi
 
       - name: Create SPA .htaccess
         run: |
@@ -50,9 +57,9 @@ jobs:
           local-dir: dist/
           server-dir: /genius/
           dangerous-clean-slate: false
-          dry-run: false
           log-level: verbose
           exclude: |
             **/.git*
             **/.github/**
             **/node_modules/**
+            **/.env*
